# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Amelia Septia Roza
email: ameliaseptiaroza@gmail.com
description: Hello. Welcome to my blog. My Name is Amelia Septia Roza. You can call me Amel.
baseurl: '/ameliaseptia.github.io/'
url: 'http://ameliaseptia.github.io'
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
